/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    RBreadcrumb: typeof import('./src/components/RBreadcrumb.vue')['default']
    RButton: typeof import('./src/components/form/RButton.vue')['default']
    RInput: typeof import('./src/components/form/RInput.vue')['default']
    RLink: typeof import('./src/components/form/RLink.vue')['default']
    RMarkDown: typeof import('./src/components/markdown/RMarkDown.vue')['default']
    RNotification: typeof import('./src/components/RNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RWangEditor: typeof import('./src/components/markdown/RWangEditor.vue')['default']
    RWangRditor: typeof import("./src/components/markdown/RWangEditor.vue")["default"]
  }
}
