/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/AnimateList.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FormRButton: typeof import('./../src/components/form/RButton.vue')['default']
    FormRInput: typeof import('./../src/components/form/RInput.vue')['default']
    FormRLink: typeof import('./../src/components/form/RLink.vue')['default']
    MarkdownRMarkDown: typeof import('./../src/components/markdown/RMarkDown.vue')['default']
    MarkdownRWangEditor: typeof import('./../src/components/markdown/RWangEditor.vue')['default']
    RBreadcrumb: typeof import('./../src/components/RBreadcrumb.vue')['default']
    RNotification: typeof import('./../src/components/RNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
